// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: log-svc.proto

package logsvc_proto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterLogSvcOrionServer registers LogSvc to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterLogSvcOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_LogSvc_serviceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterLogSvcDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "LogSvc", encoder)
}

// DefaultDecoder
func RegisterLogSvcDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "LogSvc", decoder)
}
