package orion

import (
	"github.com/carousell/Orion/v2/orion/handlers"
)

//RegisterMethodOption allows for registering an handler option to a particular method
//Note: this is normally called from protoc-gen-orion autogenerated files
func RegisterMethodOption(svr Server, serviceName, method, option string) {
	if e, ok := svr.(handlers.Optionable); ok {
		e.AddOption(serviceName, method, option)
	}
}

//RegisterMiddleware allows for registering  middlewares to a particular method
//Note: this is normally called from protoc-gen-orion autogenerated files
func RegisterMiddleware(svr Server, serviceName, method string, middleware ...string) {
	if e, ok := svr.(handlers.Middlewareable); ok {
		e.AddMiddleware(serviceName, method, middleware...)
	}
}
