language: go
sudo: false

go:
  - "1.12.x"
  - "1.16.x"
  - "1.17.x"
  - "1.18.x"
  - tip

env:
  - GO111MODULE=on

install: true

script:
  - GO111MODULE=auto go get -u golang.org/x/lint/golint
  - make ci

matrix:
  allow_failures:
    - go: master

after_success:
  - bash <(curl -s https://codecov.io/bash)