language: go
sudo: false

go:
  - "1.17.x"
  - "1.18.x"
  - master

install: true

script:
  - go get -u golang.org/x/lint/golint
  - make ci

matrix:
  allow_failures:
    - go: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
