language: go
sudo: false

go:
  - "1.12.x"

env:
  - GO111MODULE=on

install: true

script:
  - GO111MODULE=auto go get -u golang.org/x/lint/golint
  - make ci

matrix:
  allow_failures:
    - go: master
