// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: bar/bar.proto

package bar

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterBarServiceOrionServer registers BarService to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterBarServiceOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_BarService_serviceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterBarServiceDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "BarService", encoder)
}

// DefaultDecoder
func RegisterBarServiceDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "BarService", decoder)
}

