// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: echo.proto

package echo_proto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

func RegisterEchoServiceUpperEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterEncoders(svr, "EchoService", "Upper", []string{"GET", "POST", "OPTIONS"}, "/api/1.0/upper/{msg}", encoder)
}

func RegisterEchoServiceUpperHandler(svr orion.Server, handler orion.HTTPHandler) {
	orion.RegisterHandler(svr, "EchoService", "Upper", "/api/1.0/upper/{msg}", handler)
}

func RegisterEchoServiceUpperDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDecoder(svr, "EchoService", "Upper", decoder)
}

func RegisterEchoServiceUpperProxyEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterEncoders(svr, "EchoService", "UpperProxy", []string{"POST", "PUT"}, "", encoder)
}

func RegisterEchoServiceUpperProxyDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDecoder(svr, "EchoService", "UpperProxy", decoder)
}

func RegisterEchoServiceOrionServer(srv orion.ServiceFactory, orionServer orion.Server) {
	orionServer.RegisterService(&_EchoService_serviceDesc, srv)
	RegisterEchoServiceUpperEncoder(orionServer, nil)
	RegisterEchoServiceUpperProxyEncoder(orionServer, nil)
}
