// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: echo.proto

package echo_proto

import (
	orion "github.com/carousell/Orion/orion"
)

func RegisterEchoServiceOrionServer(srv EchoServiceServer, orionServer orion.Server) {
	orionServer.RegisterService(&_EchoService_serviceDesc, srv)
}
