[ServiceName]
env="development"
GRPCPort="9281"
HTTPPort="9282"
HystrixPort="9283"
PprofPort="9284"
ZipkinAddr="http://10.140.15.230:9411/api/v1/spans"

[new-relic]
api-key=""

[rollbar]
token=""

[storage-cas]
keyspace="framework"
hosts=["10.200.0.31"]
consistency="one"
connectTimeout=2000
operationTimeout=1000
connections=4

[storage-es]
url="http://10.200.0.31:9200"
prefix="framework_"
fakeContext=true
