// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: stringproto.proto

package stringproto

import (
	orion "github.com/carousell/Orion/v2/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion/v2'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterStringServiceOrionServer registers StringService to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterStringServiceOrionServer(srv interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_StringService_serviceDesc, srv)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterStringServiceDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "StringService", encoder)
}

// DefaultDecoder
func RegisterStringServiceDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "StringService", decoder)
}
