// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: stringproto.proto

package stringproto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

func RegisterStringServiceOrionServer(srv orion.ServiceFactory, orionServer orion.Server) {
	orionServer.RegisterService(&_StringService_serviceDesc, srv)
}
