// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: simple.proto

package simple_proto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterSimpleServiceOrionServer registers SimpleService to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterSimpleServiceOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&SimpleService_ServiceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterSimpleServiceDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "SimpleService", encoder)
}

// DefaultDecoder
func RegisterSimpleServiceDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "SimpleService", decoder)
}

