// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: simple.proto

package simple_proto

import (
	orion "github.com/carousell/Orion/orion"
)

func RegisterSimpleServiceOrionServer(srv orion.ServiceFactory, orionServer orion.Server) {
	orionServer.RegisterService(&_SimpleService_serviceDesc, srv)
}
