name: CI Checks

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        runs-on:
          group: ubuntu-latest



        strategy:
          matrix:
            go: ["1.17.x", "1.18.x", "master"]

        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: ${{ matrix.go }}

        - name: Install dependencies
          run: go mod download

        - name: Build and test
          run: make ci

        - name: Upload code coverage
          run: bash <(curl -s https://codecov.io/bash)